- name: Get csr
  shell: "/opt/k8s/bin/kubectl get csr"
  run_once: true
  register: csr_res

- name: Echo csr
  debug:
    msg: "{{ csr_res.stdout }}"
  run_once: true

## 手动对kubelet server执行approve csr (CSR approving controllers 不会自动 approve kubelet server 证书签名请求，需要手动 approve)
# - name: Approve csr by your hand after wait a few mins
#   shell: "/opt/k8s/bin/kubectl get csr | grep Pending | awk '{print $1}' | xargs /opt/k8s/bin/kubectl certificate approve"
#   run_once: true
#   ignore_errors: true