- name: Copy kubernetes-v1.16.5
  copy:
    src: kubernetes-v1.16.5-01.tar.gz
    dest: /opt/k8s/work/
    mode: 0755

- name: Copy kubernetes-v1.16.5
  copy:
    src: kubernetes-v1.16.5-02.tar.gz
    dest: /opt/k8s/work/
    mode: 0755

- name: Tar zxvf kubernetes-server kube-apiserver kube-controller-manager
  shell: "cd /opt/k8s/work && tar -xzvf kubernetes-v1.16.5-01.tar.gz"

- name: Tar zxvf kubernetes-server kubelet kube-proxy kube-scheduler kubeadm
  shell: "cd /opt/k8s/work && tar -xzvf kubernetes-v1.16.5-02.tar.gz"

- name: Copy kubernetes bin 
  shell: "cp /opt/k8s/work/{kube-apiserver,kube-controller-manager,kube-proxy,kube-scheduler,kubelet,kubeadm} /opt/k8s/bin/"
  ignore_errors: true

- name: Chmod u+x /opt/k8s/bin
  shell: "chmod u+x /opt/k8s/bin/*"
