- name: Stop process
  shell: "systemctl stop kubelet kube-proxy containerd kube-proxy kube-nginx"
  ignore_errors: true

- name: Delete coredns deploy
  shell: "/opt/k8s/bin/kubectl delete deploy coredns  -n kube-system"
  ignore_errors: true

- name: Delete kubernetes-dashboard deploy
  shell: "/opt/k8s/bin/kubectl delete deploy kubernetes-dashboard  -n kube-system"
  ignore_errors: true

- name: Delete /etc/cni/net.d
  shell: "rm -rf /etc/cni/net.d"

- name: Delete kubelet dir
  shell: "rm -rf {{ K8S_DIR }}/kubelet"

- name: Delete docker dir
  shell: "rm -rf {{ DOCKER_DIR }}"

- name: Delete systemd unit file
  shell: "rm -rf /etc/systemd/system/{kubelet,docker,flanneld,kube-nginx}.service"

- name: Delete docker.service.requires flanneld unit file
  shell: "rm -rf /etc/systemd/system/docker.service.requires/flanneld.service"

- name: Delete multi-user.target.wants flanneld unit file
  shell: "rm -rf /etc/systemd/system/multi-user.target.wants/flanneld.service"

- name: Delete process dir
  shell: "rm -rf /opt/k8s/bin"

- name: Delete cert
  shell: "rm -rf /etc/kubernetes/cert"

- name: Clean iptables
  shell: "iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat"

- name: Delete calico tunl0 bridge
  shell: "ip link del tunl0"
  ignore_errors: true
